name: "Semver docker tags"
author: "Greg Holmes"
description: "Generates a list of docker tags for a given refspec"
inputs:
  token:
    description: 'Github authentication token, used to list tags on the repository'
    required: true
  registries:
    description: 'list of registries to push to, comma separated'
    required: false
    default: ''
  repository:
    description: 'name of the repository to push to, if different to the git repository name'
    required: false
    default: ''
  separator:
    description: 'Separator to use between tags'
    required: false
    default: ','
  fullname:
    description: 'Should we include registry/image in tags, or just versions'
    required: false
    default: 'true'
outputs:
  tags:
    description: "All tags that should be set on a Docker image"
  version:
    description: "The semver parsed version of the image, or the SHA if this is not tag"
runs:
  using: "docker"
  image: "docker://ghcr.io/greboid/docker-tags-action:6"
